"""creation initiale

Revision ID: 103bbbac3930
Revises:
Create Date: 2026-08-18 14:06:48.131124

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "103bbbac3930"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "culture",
            sa.Enum(
                "COTON",
                "MAIS",
                "RIZ",
                "MIL",
                "SORGHO",
                "ARACHIDE",
                "MARAICHAGE",
                "AUTRE",
                name="culture_type",
            ),
            nullable=False,
        ),
        sa.Column("marche", sa.String(length=100), nullable=False),
        sa.Column("prix_moyen", sa.Float(), nullable=False),
        sa.Column(
            "unite",
            sa.Enum("KG", "SAC", "TONNE", "PANIER", name="unite_prix"),
            nullable=False,
        ),
        sa.Column("date_releve", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("prix_moyen > 0", name="ck_prices_prix_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prices_culture"), "prices", ["culture"], unique=False)
    op.create_index(
        op.f("ix_prices_date_releve"), "prices", ["date_releve"], unique=False
    )
    op.create_index(op.f("ix_prices_marche"), "prices", ["marche"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column(
            "region",
            sa.Enum(
                "BAMAKO",
                "KAYES",
                "KOULIKORO",
                "SIKASSO",
                "SEGOU",
                "MOPTI",
                "TOMBOUCTOU",
                "GAO",
                "KIDAL",
                "MENAKA",
                "TAOUDENIT",
                name="region_mali",
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("FARMER", "AGRONOMIST", "ADMIN", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "language", sa.Enum("FRENCH", "BAMBARA", name="language"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number", name="uq_users_phone_number"),
    )
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    op.create_table(
        "parcelles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("superficie_ha", sa.Float(), nullable=False),
        sa.Column(
            "culture",
            sa.Enum(
                "COTON",
                "MAIS",
                "RIZ",
                "MIL",
                "SORGHO",
                "ARACHIDE",
                "MARAICHAGE",
                "AUTRE",
                name="culture_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "region",
            sa.Enum(
                "BAMAKO",
                "KAYES",
                "KOULIKORO",
                "SIKASSO",
                "SEGOU",
                "MOPTI",
                "TOMBOUCTOU",
                "GAO",
                "KIDAL",
                "MENAKA",
                "TAOUDENIT",
                name="region_mali",
            ),
            nullable=False,
        ),
        sa.Column("commune", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "superficie_ha > 0", name="ck_parcelles_superficie_positive"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parcelles_culture"), "parcelles", ["culture"], unique=False
    )
    op.create_index(
        op.f("ix_parcelles_owner_id"), "parcelles", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_parcelles_region"), "parcelles", ["region"], unique=False)
    op.create_table(
        "diagnostics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parcelle_id", sa.Integer(), nullable=False),
        sa.Column("symptomes_observes", sa.String(length=1000), nullable=False),
        sa.Column("pathologie_detectee", sa.String(length=255), nullable=True),
        sa.Column(
            "niveau_severite",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity_level"),
            nullable=False,
        ),
        sa.Column("recommandations", sa.String(), nullable=False),
        sa.Column("score_confiance", sa.Float(), nullable=False),
        sa.Column("predictions", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "score_confiance >= 0 AND score_confiance <= 1",
            name="ck_diagnostics_score_confiance_range",
        ),
        sa.ForeignKeyConstraint(["parcelle_id"], ["parcelles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostics_parcelle_id"), "diagnostics", ["parcelle_id"], unique=False
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parcelle_id", sa.Integer(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "SEMIS",
                "IRRIGATION",
                "FERTILISATION",
                "TRAITEMENT",
                "DESHERBAGE",
                "RECOLTE",
                "OBSERVATION",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("cout_fcfa", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cout_fcfa >= 0", name="ck_journal_entries_cout_non_negative"
        ),
        sa.ForeignKeyConstraint(["parcelle_id"], ["parcelles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entries_action_type"),
        "journal_entries",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entries_parcelle_id"),
        "journal_entries",
        ["parcelle_id"],
        unique=False,
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parcelle_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=300), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parcelle_id"], ["parcelles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_photos_parcelle_id"), "photos", ["parcelle_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photos_parcelle_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_journal_entries_parcelle_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_action_type"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_diagnostics_parcelle_id"), table_name="diagnostics")
    op.drop_table("diagnostics")
    op.drop_index(op.f("ix_parcelles_region"), table_name="parcelles")
    op.drop_index(op.f("ix_parcelles_owner_id"), table_name="parcelles")
    op.drop_index(op.f("ix_parcelles_culture"), table_name="parcelles")
    op.drop_table("parcelles")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_prices_marche"), table_name="prices")
    op.drop_index(op.f("ix_prices_date_releve"), table_name="prices")
    op.drop_index(op.f("ix_prices_culture"), table_name="prices")
    op.drop_table("prices")

    # These PostgreSQL enum types are shared by multiple tables, so they are
    # removed explicitly only after all dependent tables have been dropped.
    op.execute("DROP TYPE IF EXISTS action_type")
    op.execute("DROP TYPE IF EXISTS severity_level")
    op.execute("DROP TYPE IF EXISTS language")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS region_mali")
    op.execute("DROP TYPE IF EXISTS unite_prix")
    op.execute("DROP TYPE IF EXISTS culture_type")
    # ### end Alembic commands ###
